import {useEffect,useRef,useState} from 'react';
import {gsap} from 'gsap'; import {ScrollTrigger} from 'gsap/ScrollTrigger'; import {useGSAP} from '@gsap/react';
import {siteContent as c} from './data/siteContent';
import {PageShell} from './pages/PageShell';
import {CurvedMenu,type MenuItem} from './components/ui/curved-menu';
import {FlyingPhoenix} from './components/FlyingPhoenix';
import {HomeActivity,KidsActivityPage} from './pages/KidsActivityPage';
import {TeamShowcase} from './components/ui/team-showcase';
import {ManzilFeature} from './components/ManzilFeature';
gsap.registerPlugin(ScrollTrigger,useGSAP);
const frame=(n:number)=>`/assets/hero/frames/ezgif-frame-${String(n).padStart(3,'0')}.jpg`;
const menuNotes=['Enter the enchanted forest','Meet the imagination behind the story','Discover every book and world','Explore the hand-painted artwork','Play, create, and learn together','Send a note to Vaani'];
const menuItems:MenuItem[]=c.nav.map(([heading,href],i)=>({heading,href,subheading:menuNotes[i]}));

function Loader({done}:{done:boolean}){return <div className={`loader ${done?'done':''}`} aria-hidden={done}><img src="/assets/brand/vaani-logo.png"/><p>The forest is awakening…</p><span/></div>}
function ShapeTransition(){const overlay=useRef<SVGSVGElement>(null);useGSAP(()=>{const svg=overlay.current!;const paths=Array.from(svg.querySelectorAll<SVGPathElement>('path'));const count=10;const sets=paths.map(()=>Array(count).fill(100) as number[]);const render=()=>sets.forEach((points,i)=>{let d=`M 0 ${points[0]} C`;for(let j=0;j<count-1;j++){const p=(j+1)/(count-1)*100,cp=p-50/(count-1);d+=` ${cp} ${points[j]} ${cp} ${points[j+1]} ${p} ${points[j+1]}`}paths[i].setAttribute('d',`${d} V 100 H 0 Z`)});render();const play=()=>{gsap.set(svg,{autoAlpha:1});const delays=Array.from({length:count},()=>Math.random()*.16);const tl=gsap.timeline({onUpdate:render,onComplete:()=>gsap.set(svg,{autoAlpha:0})});sets.forEach((points,i)=>points.forEach((_,j)=>tl.to(points,{[j]:0,duration:.5,ease:'power2.inOut'},delays[j]+i*.12)));tl.addLabel('reveal','>-.02');[...sets].reverse().forEach((points,i)=>points.forEach((_,j)=>tl.to(points,{[j]:100,duration:.65,ease:'power2.inOut'},`reveal+=${delays[j]+i*.12}`)))};ScrollTrigger.create({trigger:'#story',start:'top bottom',onEnter:play,onLeaveBack:play})},{scope:overlay});return <svg ref={overlay} className="shape-overlays" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="forest-wash" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#f5b63a"/><stop offset=".52" stopColor="#f26a65"/><stop offset="1" stopColor="#fff8e8"/></linearGradient><linearGradient id="canopy-wash" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#173f35"/><stop offset="1" stopColor="#77cfc2"/></linearGradient></defs><path fill="url(#forest-wash)"/><path fill="url(#canopy-wash)"/></svg>}
function Hero({onReady}:{onReady:()=>void}){
 const root=useRef<HTMLElement>(null),canvas=useRef(document.createElement('canvas')),video=useRef<HTMLVideoElement>(null); const [scene,setScene]=useState(0);
 useEffect(()=>{const el=canvas.current;el.setAttribute('aria-label','Animated forest story');root.current!.prepend(el);return()=>el.remove()},[]);
 useGSAP(()=>{const el=canvas.current!,ctx=el.getContext('2d',{alpha:false})!;const images=Array.from({length:50},(_,i)=>{const image=new Image();image.decoding='async';image.src=frame(i+1);return image});let wanted=0,displayed=0,raf=0,lastFrame=-1,lastScene=-1,alive=true;const draw=(index:number)=>{const image=images[index];if(!image.complete||!image.naturalWidth)return;const dpr=Math.min(devicePixelRatio||1,2),w=el.clientWidth,h=el.clientHeight,pw=Math.round(w*dpr),ph=Math.round(h*dpr);if(el.width!==pw||el.height!==ph){el.width=pw;el.height=ph}const cover=Math.max(pw/image.naturalWidth,ph/image.naturalHeight),mobile=w<700&&h>w,coverW=image.naturalWidth*cover,coverH=image.naturalHeight*cover;ctx.filter=mobile?'blur(22px) brightness(.72)':'none';ctx.drawImage(image,(pw-coverW)/2,(ph-coverH)/2,coverW,coverH);if(mobile){const contain=Math.min(pw/image.naturalWidth,ph/image.naturalHeight),dw=image.naturalWidth*contain,dh=image.naturalHeight*contain;ctx.filter='none';ctx.drawImage(image,(pw-dw)/2,(ph-dh)/2,dw,dh)}ctx.filter='none'};const render=()=>{displayed+=(wanted-displayed)*.12;if(Math.abs(wanted-displayed)<.0003)displayed=wanted;const nextFrame=Math.min(images.length-1,Math.round(displayed*(images.length-1)));if(nextFrame!==lastFrame){lastFrame=nextFrame;draw(nextFrame)}const nextScene=Math.min(c.heroScenes.length-1,Math.floor(displayed*c.heroScenes.length));if(nextScene!==lastScene){lastScene=nextScene;setScene(nextScene)}raf=requestAnimationFrame(render)};const resize=()=>{lastFrame=-1};addEventListener('resize',resize,{passive:true});Promise.all(images.map(image=>image.decode().catch(()=>Promise.resolve()))).then(()=>{if(alive){draw(lastFrame<0?0:lastFrame);onReady()}});images[0].addEventListener('load',()=>draw(0),{once:true});raf=requestAnimationFrame(render);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced)ScrollTrigger.create({trigger:root.current,start:'top top',end:'+=105%',pin:true,anticipatePin:1,invalidateOnRefresh:true,onUpdate:self=>{wanted=self.progress}});return()=>{alive=false;cancelAnimationFrame(raf);removeEventListener('resize',resize)}},{scope:root});
 const copy=c.heroScenes[scene];
 return <section ref={root} id="top" className="hero videoHero"><video ref={video} muted playsInline preload="auto" poster="/assets/hero/frames/ezgif-frame-001.jpg"><source src="/assets/video/animals-gathering-at-magical-tree.mp4" type="video/mp4"/></video><div className="heroShade"/><div className="heroCopy" key={scene}><p className="eyebrow">{copy.eyebrow}</p><h1>{copy.title}</h1><p className="sub">{copy.subtitle}</p><div className="actions"><a className="button primary" href="#story">Explore the forest <b>↘</b></a><a className="button ghost" href="#preview">Preview the book</a></div></div><div className="sceneCount" key={`count-${scene}`}><span>0{scene+1}</span><i/><span>0{c.heroScenes.length}</span></div><div className="scrollCue"><span/>Scroll to move the story</div></section>
}
function SectionTitle({kicker,title}:{kicker:string,title:string}){return <div className="sectionTitle"><span>{kicker}</span><h2>{title}</h2></div>}
function Story(){const root=useRef<HTMLElement>(null);useGSAP(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)return;gsap.from('.authorIntroVisual',{scale:.86,rotation:-3,opacity:0,duration:1.1,ease:'power3.out',scrollTrigger:{trigger:root.current,start:'top 78%'}});gsap.from('.authorIntroCopy > *',{y:34,opacity:0,duration:.8,stagger:.1,ease:'power2.out',scrollTrigger:{trigger:root.current,start:'top 72%'}});gsap.to('.authorOrbit',{rotation:360,duration:28,repeat:-1,ease:'none'})},{scope:root});return <section ref={root} id="story" className="authorIntro"><video className="authorBg" autoPlay muted loop playsInline preload="metadata" aria-hidden="true"><source src="/assets/video/animals-gathering-at-magical-tree.mp4" type="video/mp4"/></video><div className="authorBgShade"/><div className="authorIntroVisual"><div className="authorHalo"/><div className="authorOrbit" aria-hidden="true"><span>IMAGINATION</span><i>✦</i><span>KINDNESS</span><i>✦</i><span>WONDER</span><i>✦</i></div><div className="authorPortrait"><img src="/assets/author-writing-child.png" alt="Young writer holding a pencil and notebook"/></div><div className="authorNote"><b>Author of</b><span>The Soul of<br/>the Forest</span></div></div><div className="authorIntroCopy"><p className="eyebrow">Meet the imagination behind the forest</p><h2>Stories begin with <em>a little wonder.</em></h2><p className="authorLead">Vaani Halwasiya is the creative voice behind <i>The Soul of the Forest</i>—a magical world shaped by kindness, community, motherhood, and the courage to be heard.</p><div className="authorValues"><span><b>01</b>Kindness</span><span><b>02</b>Community</span><span><b>03</b>Finding your voice</span></div><a href="/about" className="authorLink">Discover Vaani’s story <b>↗</b></a></div></section>}
const characterShowcase=[
 {name:'Nancy',role:'The courageous rabbit',imageSrc:'/assets/characters/nancy.png',themeColor:'#f7d4d8'},
 {name:'Bumpy',role:'The warm-hearted camel',imageSrc:'/assets/characters/bumpy.png',themeColor:'#d4e7e5'},
 {name:'Voz',role:'The colourful songbird',imageSrc:'/assets/characters/voz.png',themeColor:'#fce7bd'},
 {name:'Knotty',role:'The curious snake',imageSrc:'/assets/characters/knotty.png',themeColor:'#e9e0d7'},
 {name:'Mona',role:'The playful monkey',imageSrc:'/assets/characters/mona.png',themeColor:'#ded4e9'}
];
function Characters(){return <TeamShowcase title="Friends among the leaves" description="Every corner of the forest holds a different kind of friend. Nancy brings courage, Bumpy carries warmth, Knotty keeps everyone smiling, Voz fills the trees with colour and song, and Mona turns every ordinary moment into a playful adventure." members={characterShowcase}/>}
function Heart(){return <section className="heart"><img src={frame(24)} alt="The magical tree glowing in the forest"/><div className="heartCard"><span>THE HEART OF THE STORY</span><h2>Kindness is a gift that keeps growing.</h2><p>In this forest, every friend has something special to offer—and every voice deserves to be heard.</p></div></section>}
const gallery=[12,23,31,38,44];
// Legacy illustration viewer retained for possible reuse.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function Gallery(){const [active,setActive]=useState<number|null>(null);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(active===null)return;if(e.key==='Escape')setActive(null);if(e.key==='ArrowRight')setActive((active+1)%gallery.length);if(e.key==='ArrowLeft')setActive((active-1+gallery.length)%gallery.length)};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[active]);return <section id="gallery" className="gallery wrap"><SectionTitle kicker="From the sketchbook" title="A world painted in wonder"/><div className="galleryGrid">{gallery.map((n,i)=><button key={n} onClick={()=>setActive(i)}><img loading="lazy" src={frame(n)} alt={`Illustrated forest scene ${i+1}`}/><span>View scene ↗</span></button>)}</div>{active!==null&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Illustration viewer" onClick={()=>setActive(null)}><button aria-label="Close">×</button><img src={frame(gallery[active])} alt={`Illustrated forest scene ${active+1}`}/></div>}</section>}
function Preview(){const pages=[1,10,20,30,40,50];const [p,setP]=useState(0);return <section id="preview" className="preview"><div className="wrap previewHead"><SectionTitle kicker="A little peek inside" title="Turn a page. Find a feeling."/><p>A curated glimpse into the colour, warmth, and characters of the forest.</p></div><div className="book"><div className="page"><img src={frame(pages[p])} alt={`Book preview scene ${p+1}`}/><span>{p+1} / {pages.length}</span></div><div className="bookControls"><button onClick={()=>setP((p-1+pages.length)%pages.length)} aria-label="Previous preview">←</button><div>{pages.map((_,i)=><button key={i} className={i===p?'active':''} onClick={()=>setP(i)} aria-label={`Open preview ${i+1}`}/>)}</div><button onClick={()=>setP((p+1)%pages.length)} aria-label="Next preview">→</button></div></div></section>}
function Author(){return <section id="author" className="bookFeature"><div className="bookFeatureCopy"><p className="bookEyebrow">The featured story</p><h2>A little voice.<br/><em>A forest full of heart.</em></h2><p className="bookDescription"><i>The Soul of the Forest</i> is a warmly illustrated story about kindness, community, motherhood, and the courage to be heard. Follow Voz and her forest friends into a world where even the smallest voice can make a beautiful difference.</p><blockquote>“A keepsake story for curious minds and kind hearts.”</blockquote><div className="bookDetails"><span><b>Perfect for</b>Young readers & families</span><span><b>Inside</b>A richly illustrated adventure</span></div><a className="bookBuy" href={c.purchaseUrl||'/contact'}>Buy your copy now <b>↗</b></a></div><div className="bookMockupScene"><div className="bookAura"/><div className="bookMockup"><div className="bookSpine"><span>THE SOUL OF THE FOREST</span></div><div className="bookCover"><img src={frame(24)} alt="The Soul of the Forest book cover artwork"/><div className="bookCoverShade"/><span>A magical story by</span><h3>The Soul<br/>of the Forest</h3><p>Vaani Halwasiya</p></div><div className="bookPages"/></div><div className="bookSeal"><span>Illustrated<br/>storybook</span><b>✦</b></div><p className="bookCaption">A story to read together—and remember.</p></div></section>}
function Faq(){const [open,setOpen]=useState(0);return <section id="faqs" className="faq wrap"><SectionTitle kicker="Curious little minds" title="Questions from the forest"/><div>{c.faqs.map(([q,a],i)=><article key={q}><button aria-expanded={open===i} onClick={()=>setOpen(open===i?-1:i)}><span>{String(i+1).padStart(2,'0')}</span>{q}<b>{open===i?'−':'+'}</b></button><div className={open===i?'open':''}><p>{a}</p></div></article>)}</div></section>}
function Footer(){return <footer className="editorialFooter"><div className="footerTop"><p>Stories beyond the expected</p><h2>The next chapter<br/>starts with a <em>conversation.</em></h2><a href="/contact">Connect with Vaani <b>↗</b></a></div><div className="footerDirectory"><div className="footerIdentity"><img src="/assets/brand/vaani-logo.png" alt="Vaani Halwasiya"/><p>Author and storyteller creating imaginative worlds shaped by kindness, community, and courageous little voices.</p></div><nav aria-label="Footer navigation"><div><b>Explore</b><a href="/">Home</a><a href="/about">About Vaani</a><a href="/bookshelf">Book shelf</a><a href="/illustration">Illustration</a></div><div><b>Discover</b><a href="/kids-activity">Kids activity</a><a href="#faqs">Questions</a><a href="/contact">Contact</a></div></nav></div><div className="footerWordmark" aria-label="Vaani Halwasiya">VAANI</div><div className="foot"><p>© {new Date().getFullYear()} Vaani Halwasiya. All rights reserved.</p><a href="#top">Back to top ↑</a><span>Stories rooted in kindness</span></div></footer>}
export default function App(){const [ready,setReady]=useState(false);const path=window.location.pathname.replace(/\/$/,'')||'/';useGSAP(()=>{gsap.utils.toArray<HTMLElement>('.sectionTitle, .characterGrid article').forEach(el=>gsap.from(el,{y:40,opacity:0,duration:.8,scrollTrigger:{trigger:el,start:'top 88%'}}))});if(path==='/kids-activity')return <><CurvedMenu items={menuItems}/><KidsActivityPage/><Footer/></>;if(path!=='/'){const page=path.slice(1) as 'about'|'bookshelf'|'illustration'|'contact';if(['about','bookshelf','illustration','contact'].includes(page))return <><CurvedMenu items={menuItems}/><PageShell page={page}/><Footer/></>}return <><a className="skip" href="#story">Skip to content</a><Loader done={ready}/><ShapeTransition/><CurvedMenu items={menuItems}/><FlyingPhoenix/><main><Hero onReady={()=>setReady(true)}/><Story/><Characters/><Heart/><ManzilFeature/><HomeActivity/><Preview/><Author/><Faq/></main><Footer/></>}
